CMAKE_MINIMUM_REQUIRED(VERSION 3.5.0 FATAL_ERROR)

PROJECT(mimalloc-download NONE)

INCLUDE(ExternalProject)
ExternalProject_Add(mimalloc
	GIT_REPOSITORY https://github.com/microsoft/mimalloc
	GIT_TAG master
	SOURCE_DIR "${DNN_DEPENDENCIES_SOURCE_DIR}/mimalloc"
	BINARY_DIR "${DNN_DEPENDENCIES_BINARY_DIR}/mimalloc"
	CONFIGURE_COMMAND ""
	BUILD_COMMAND ""
	INSTALL_COMMAND ""
	TEST_COMMAND ""
)
