CMAKE_MINIMUM_REQUIRED(VERSION 3.5.0 FATAL_ERROR)

PROJECT(version2-download NONE)

INCLUDE(ExternalProject)
ExternalProject_Add(vectorclass
	GIT_REPOSITORY https://github.com/uapconvnet/version2
	GIT_TAG main
	SOURCE_DIR "${DNN_DEPENDENCIES_SOURCE_DIR}/version2"
	BINARY_DIR "${DNN_DEPENDENCIES_BINARY_DIR}/version2"
	CONFIGURE_COMMAND ""
	BUILD_COMMAND ""
	INSTALL_COMMAND ""
	TEST_COMMAND ""
)