CMAKE_MINIMUM_REQUIRED(VERSION 3.5.0 FATAL_ERROR)

PROJECT(cimg-download NONE)

INCLUDE(ExternalProject)
ExternalProject_Add(cimg
	GIT_REPOSITORY https://github.com/dtschump/CImg.git
	GIT_TAG master
	SOURCE_DIR "${DNN_DEPENDENCIES_SOURCE_DIR}/CImg"
	BINARY_DIR "${DNN_DEPENDENCIES_BINARY_DIR}/CImg"
	CONFIGURE_COMMAND ""
	BUILD_COMMAND ""
	INSTALL_COMMAND ""
	TEST_COMMAND ""
)